require("config.options")
require("config.lazy")
require("config.keymaps")
require("config.lsp_config")
-- require("config.snacks_things")
require('config.mini-files-setup')
require('config.lsp_ferrodata')
-- require('config.lsp_dbt_lsp')
