-- local snk = require("snacks")
-- -- Floating Terminal
-- vim.keymap.set("n", "<leader>tt", function()
--     snk.terminal.toggle(
--         vim.o.shell,
--         {
--             win = {
--                 position = 'bottom',
--                 height = 0.3
--             }
--         }
--     )
-- end, {
--     desc = "Toggle Floating Terminal"
-- })
