return {}
-- return {
--     "nvim-tree/nvim-tree.lua",
--     version = "*",
--     lazy = false,
--     dependencies = {
--         "nvim-tree/nvim-web-devicons",
--     },
--     config = function()
--         require("nvim-tree").setup {
--             git = {
--                 enable = true,
--                 timeout = 3000
--             }
--         }
--         vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>", { desc = "Nvim Tree Toggle" })
--     end,
-- }
